micronaut:
  application:
    name: complete
---
#tag::security[]
micronaut:
  security:
    enabled: true # <1>
    endpoints:
      login:
        enabled: true # <2>
      logout:
        enabled: true # <3>
    session:
      enabled: true # <4>
      login-success-target-url: / # <5>
      login-failure-target-url: /login/authFailed # <6>
#end::security[]